---
title: "EDS 212 Day 2 Tasks"
author: "Nicole Pepper"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# Load Libraries
library(tidyverse)
library(palmerpenguins)
data(package='palmerpenguins')
penguins <- penguins
```

```{r}
# Connect with your Git
#usethis::use_git()
# Connect with your GitHub
#usethis::use_github()
```

#Finding derivaties using R

```{r}
# Create an expression

ex1 <- expression(x^2)

# Take the derivative

der_ex1_x <- D(expr = ex1, name = "x")
der_ex1_x

# Evaluate the expression
x <- 3
eval(der_ex1_x)

# Create an expression 
ex2 <- expression(2 * (3*a + 2)^4 - 5)
ex2

# Take the derivative
der_ex2_a <- D(expr = ex2, name = "a")
der_ex2_a

# Evaluate the expression
a <- 1.2
eval(der_ex2_a)
```

#Now onto Penguins

```{r}
#create a plot in ggplot

ggplot(data = penguins, aes (x = bill_length_mm, y = bill_depth_mm)) + geom_point(aes(color = species)) + labs( title = "Penguin bills", x = "Bill Length (mm)", y = "Bill Depth (mm)")



ggplot(data = penguins, aes (x = species, y = flipper_length_mm)) + geom_jitter(aes(color = species)) + labs( title = "Penguin flippers", x = "Penguin Species", y = "Flipper Length (mm)")


```

